Starting step 0
test
python: can't open file 'run_tracing.py': [Errno 2] No such file or directory
