Cpus_allowed_list:	1,3,5-6,8,10-13,15,17-18
STEP0 SLURM
/scratch/ejdennis/cm2_brains/m128/488
smartspim
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/2333', please create it with 0700 permissions.
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/vispy/visuals/line/line.py:395: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/vispy/visuals/line/arrow.py:57: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
about to import workspace
starting
Traceback (most recent call last):
  File "cell_detect.py", line 57, in <module>
    jobid = int(os.environ["SLURM_ARRAY_TASK_ID"])
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_ARRAY_TASK_ID'
