In the directory: /jukebox/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster 
As the user: zmd 
on host: spock7-c0-10 
Cpus_allowed_list:	0,2,4,6,8,10,12
Array Allocation Number: 18761218
Array Index: 0
['run_clearmap_cluster.py', '6', '0']
0
setting elastixlib path as /jukebox/pkgs/ELASTIX/4.8/bin, ***note this is a hack and may fail***
Elastix sucessfully initialized from path: /jukebox/pkgs/ELASTIX/4.8
list index out of range
Traceback (most recent call last):
  File "run_clearmap_cluster.py", line 138, in <module>
    output_analysis(threshold = (1500, 10000), row = (2,2), check_cell_detection = False, **params) #note: zmd has set threshold and 
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/cluster/par_tools.py", line 187, in output_analysis
    points = transformPoints(points, transformDirectory = dct["CorrectionAlignmentParameter"]["resultDirectory"], indices = False, resultDirectory = None);
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/Alignment/Elastix.py", line 748, in transformPoints
    transformparameterfile = getTransformParameterFile(transformparameterdir);
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/Alignment/Elastix.py", line 232, in getTransformParameterFile
    raise RuntimeError('Cannot find a valid transformation file in ' + resultdir);
RuntimeError: Cannot find a valid transformation file in /jukebox/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/clearmap_cluster_output/elastix_cfos_to_auto
