Traceback (most recent call last):
  File "/mnt/sink/scratch/ejdennis/rat_BrainPipe/tools/utils/io.py", line 305, in dict_update
    with open(pth, 'rb') as pckl:
IsADirectoryError: [Errno 21] Is a directory: '/scratch/ejdennis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cell_detect.py", line 179, in <module>
    main(**vars(args))
  File "cell_detect.py", line 25, in main
    params = fill_params(**args)
  File "cell_detect.py", line 106, in fill_params
    kwargs = load_kwargs(os.path.dirname(expt_name))
  File "/mnt/sink/scratch/ejdennis/rat_BrainPipe/tools/utils/io.py", line 416, in load_kwargs
    dict_update(kwargs['outputdirectory'], old_system_directory=system_directories)
  File "/mnt/sink/scratch/ejdennis/rat_BrainPipe/tools/utils/io.py", line 310, in dict_update
    with open(pth, 'rb') as pckl:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/ejdennis/param_dict.p'
